/**
 * @fileoverview Simulated annealing global optimizer.
 *
 * Metropolis-Hastings-style search with a geometric cooling schedule.
 * Each iteration proposes a Gaussian-ish neighbor of the current point
 * (`stepSize` controls the width) and accepts it with probability
 *
 *     p = min(1, exp(-delta / temp))
 *
 * where `delta = f(neighbor) - f(current)`. The best-ever point is
 * tracked alongside the current iterate.
 *
 * Routed randomness comes from `prng.js`, so the schedule is reproducible
 * across calls that share the same seed.
 */

import {random} from '../prng.js';

/**
 * Simulated-annealing minimization over an arbitrary-dimensional space.
 *
 * The neighbor for each iteration is generated by perturbing every
 * coordinate by a uniform offset in `[-stepSize, stepSize]`. The
 * acceptance temperature decays geometrically: `temp *= coolingRate`. The
 * loop terminates once either `maxIter` iterations are performed or the
 * temperature drops below `finalTemp`.
 *
 * @param {function(Array<number>): number} f Objective function.
 * @param {Array<number>} x0 Initial guess.
 * @param {Object} opts Algorithm options.
 * @param {number=} opts.maxIter Maximum iterations (default `5000`).
 * @param {number=} opts.initialTemp Initial temperature (default `100`).
 * @param {number=} opts.finalTemp Temperature cut-off (default `0.001`).
 * @param {number=} opts.coolingRate Per-iteration multiplier (default
 *   `0.995`).
 * @param {number=} opts.stepSize Half-width of the uniform proposal
 *   distribution (default `0.1`).
 * @return {{x: Array<number>, f: number}} The best point found and its
 *   function value.
 */
export function simulatedAnnealing(f, x0, opts = {}) {
  const maxIter = opts.maxIter || 5000;
  const initialTemp = opts.initialTemp || 100;
  const finalTemp = opts.finalTemp || 0.001;
  const coolingRate = opts.coolingRate || 0.995;
  const stepSize = opts.stepSize || 0.1;

  let current = [...x0];
  let currentValue = f(current);
  let best = [...current];
  let bestValue = currentValue;

  let temp = initialTemp;

  for (let iter = 0; iter < maxIter && temp > finalTemp; iter++) {
    const neighbor = current.map((val) => {
      const delta = (random() - 0.5) * 2 * stepSize;
      return val + delta;
    });
    const neighborValue = f(neighbor);
    const delta = neighborValue - currentValue;

    // Clamp the exponent at 700 to avoid `Math.exp` overflow on `Infinity`
    // inputs; in practice this only happens when `delta` is large and
    // positive (bad move) and `temp` is very small.
    const acceptanceProb = Math.exp(Math.min(700, -delta / temp));
    if (delta < 0 || random() < acceptanceProb) {
      current = neighbor;
      currentValue = neighborValue;
      if (currentValue < bestValue) {
        best = [...current];
        bestValue = currentValue;
      }
    }
    temp *= coolingRate;
  }

  return {x: best, f: bestValue};
}
